version: 2.1

defaults: &defaults
  working_directory: ~/grommet-ci
  docker:
    - image: circleci/node:14

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      - run: yarn --frozen-lockfile
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
            - ./node_modules
      - persist_to_workspace:
          root: ~/grommet-ci
          paths:
            - ./
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/grommet-ci
      - run:
          name: Build
          command: yarn build
          working_directory: packages/project-scripts
      - persist_to_workspace:
          root: ~/grommet-ci
          paths:
            - ./
  release-stable:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/grommet-ci
      - run:
          command: |
            git config --global user.name "Taylor Seamans"
            git config --global user.email "taylor.seamans@yahoo.com"
            yarn release-stable
          working_directory: packages/project-scripts
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/grommet-ci
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/grommet-ci/dist/.npmrc
      - run:
          name: Add npmignore
          command: echo "**/__tests__/**" > ~/grommet-ci/dist/.npmignore
      - run:
          name: Publish package
          command: cd dist && npm publish
workflows:
  build_test:
    jobs:
      - checkout:
          filters:
            tags:
              only: /.*/
      - build:
        requires:
          - checkout
        filters:
          tags:
            only: /.*/
          branches:
            ignore:
              - stable
      - release-stable:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
